openapi: 3.0.0
info:
   title: "Transactions API"
   version: 1.0.0
paths:
  /api/transaction/sum:
    get:
      operationId: calculateSum
      parameters:
        - name: q
          in: query
          required: true
          style: deepObject
          explode: true
          schema:
            title: CalculateSumQuery
            type: object
            properties:
              from:
                type: array
                items:
                  type: string
              to:
                type: array
                items:
                  type: string
      responses:
        200:
          description: sum
          content:
            application/json:
              schema:
                type: number
                format: double
  /api/transactions:
    get:
      operationId: getTransactionsList
      parameters:
        - name: from
          in: query
          description: Matches exactly the email from
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: to
          in: query
          description: Matches exactly the email to
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: message
          in: query
          description: Matches exactly or a part of message field
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: Ok
          content:
            application/json:    
              schema:
                type: array
                items:                
                  $ref: "#/components/schemas/Transaction"
        500:
          description: Something wrong happened
    put:
      operationId: putTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                batch_name:
                  type: string
                batch:
                  type: array
                  items:
                    $ref: "#/components/schemas/Transaction"
              required:
                - batch
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        500:
          description: Something wrong happened
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /sbam:
    put:
      operationId: sbamTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  addedElement:
                    $ref: "#/components/schemas/Transaction"
                  at:
                    type: string
                    format: date-time
                    
        500:
          description: Something wrong happened
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Transaction:
      type: object
      properties:
        message:
          type: string
        from:
          type: string
          format: email
        to:
          type: string
          format: email
        value:
          type: number
          format: double
      additionalProperties: false
      required:
        - message
        - from
        - to
        - value
    Error:
      type: object
      properties:
        message:
          type: string
        at:
          type: string
          format: date-time
      additionalProperties: false
      required:
        - message
        - at